# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bionic < Formula
  desc ""
  homepage "https://bionic.dev"
  version "0.0.3"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/bionic-dev/bionic/releases/download/v0.0.3/bionic_0.0.3_Darwin_x86_64.tar.gz"
    sha256 "a29a5d14390b51204300c04127eecb97b9b3fcb649d490d1fe5efdb841caf659"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bionic-dev/bionic/releases/download/v0.0.3/bionic_0.0.3_Linux_x86_64.tar.gz"
    sha256 "ae2cfb34b2fda69fc5a4fc125dd3fd130671c374d085458fc79889d36b7ab110"
  end

  def install
    bin.install "bionic"
  end
end
