# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bionic < Formula
  desc ""
  homepage "https://bionic.dev"
  version "0.0.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/bionic-dev/bionic/releases/download/v0.0.1/bionic_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "e8ceee215c3d5a64fe3e68f7a31c266d888bca512c6e2ccd1a4819f5121a7b16"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bionic-dev/bionic/releases/download/v0.0.1/bionic_0.0.1_Linux_x86_64.tar.gz"
    sha256 "0a961382efe2cdfca86810fbe21ca688c28a2234a942ae994c3ca1c0f10958ca"
  end

  def install
    bin.install "bionic"
  end
end
