# This file was generated by GoReleaser. DO NOT EDIT.
class BionicCli < Formula
  desc ""
  homepage "https://github.com/shekhirin/bionic-cli"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/shekhirin/bionic-cli/releases/download/v0.0.1/bionic-cli_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "eb1c3af6180b9c9238630b2c2162176014d2198f69075e8b79b6f72fd60f87df"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/shekhirin/bionic-cli/releases/download/v0.0.1/bionic-cli_0.0.1_Linux_x86_64.tar.gz"
    sha256 "05bb63003bcd6febb2704fe853d7f9f89a45f3b686402cb9f7786cb43e7a7dd6"
  end

  def install
    bin.install "bionic"
  end
end
